######################################################################
# Automatically generated by qmake (2.01a) ?? 30. ??? 13:43:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testsubject.cpp poly.h poly.cpp
CONFIG += qtestlib
