######################################################################
# Automatically generated by qmake (2.01a) ?? 4. ??? 14:52:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


# Input
SOURCES += main.cpp
