######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 14 14:02:29 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_dialog.h
FORMS += md.ui
SOURCES += main.cpp main_dialog.cpp
