######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 14 11:20:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp main_dialog.cpp
HEADERS += main_dialog.h
