######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 14 14:02:29 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
FORMS += md.ui
HEADERS += main_dialog.h ourgl.h
SOURCES += main.cpp main_dialog.cpp ourgl.cpp
