######################################################################
# Automatically generated by qmake (2.01a) ?? 30. ??? 13:43:10 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testpoly.cpp poly.cpp
HEADERS += poly.h
