######################################################################
# Automatically generated by qmake (2.01a) ?? 13. ??? 14:59:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += piezo_tensor.h utility.h
SOURCES += main.cpp piezo_tensor.cpp utility.cpp
