######################################################################
# Automatically generated by qmake (2.01a) ?? 16. ??? 12:43:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
