######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 14:10:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += main_dialog.h our_gl_widget.h
FORMS += dialog.ui md.ui
SOURCES += main.cpp main_dialog.cpp our_gl_widget.cpp
