######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 07:49:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lfftw3

# Input
SOURCES += main.cpp
