######################################################################
# Automatically generated by qmake (2.01a) ?? 13. ??? 14:59:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += piezo_tensor.h material_tensor.h matrix.h vector.h util.h
SOURCES += main.cpp piezo_tensor.cpp material_tensor.cpp matrix.cpp vector.cpp util.cpp
